# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_commentmodel_upvote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='upvote_count',
        ),
    ]
